### ISSUE TITLE
Not eligible still happening

### ISSUE THREAD

**Issue by Pandafishie** [hackermondev/discord-active-developer-badge#14]
Citing: 
> ![image](https://user-images.githubusercontent.com/33282375/202399462-913f40fd-9bc0-4420-a5fd-1cb8e008c28f.png)

This is, seemingly, not patched yet. Where do I find Discord's ETAs? I've followed all steps twice over 5 days with 2 different accounts. Both accounts weren't deemed eligible.

Both accounts had their respective Application + bot. Also both accounts have 2FA-enabled.

Anyone having similar issues?

**Comment by hackermondev** [comment]
Discord fixed the bug on Tuesday. Some people are now able to get the badge without doing anything else and some people have to redo everything before it says they are eligible.

You are in the second boat. You're going have to redo everything cause Discord fixed the bug yesterday.

**Comment by Zenoo** [comment]
Same issue for me, I redid it yesterday, but I seem to still be ineligible.

**Comment by Arch881010** [comment]
@Zenoo 
![BA279EBB-436F-44DE-A8CC-32F2F811DF20](https://user-images.githubusercontent.com/111789310/202583642-e2e64b88-2b7d-4955-8b3e-08db5f7753fd.jpeg)
Image took just now.
This issue is still ongoing. (CST time btw)

**Comment by hackermondev** [comment]
Yeah. Ignore my first answer, I thought everything has been fixed but it looks like there are still some issues from Discord's end.
Unfortunately, there's nothing I can do and you're gonna have to wait until Discord fixes it.

**Comment by Zenoo** [comment]
This was fixed for me this morning.

**Comment by Pandafishie** [comment]
> This was fixed for me this morning.

Officially, this is still not resolved.
Additionally, I can confirm, that this is not fixed for everybody yet. Thus, for some the wait continues, as it might seem.

**Comment by starpotion** [comment]
Same deal as of this moment, hang in there guys.

**Comment by Pandafishie** [comment]
>Rabbit Tank (Discord)
>
>Nov 21, 2022, 15:20 PST
>
>Hey again,
> 
>Thanks for your patience on this! I wanted to provide you an update that we’ve addressed the bug impacting eligibility for the Active Developer Badge, meaning you should be able to go and claim it without issue!
> 
>If you’re still having trouble claiming the badge, please make sure to review our eligibility requirements here: https://dis.gd/active-developer-badge
> 
>Additionally, in order to detect an app's command usage to determine eligibility, at least one person using the app will need to have “Use data to improve Discord” enabled under User Settings > Privacy & Safety.
> 
>Eligibility begins 24 hours after the first time we detect a command, so if you’re still ineligible make sure that we can detect your app's activity before trying again!
> 
>Please don’t hesitate to let me know if you have any other questions or concerns and I’d be happy to help further!
> 
>Best,
>Rabbit Tank
- support@discord.com

I guess the issue is resolved then.

**Comment by hackermondev** [comment]
> at least one person using the app will need to have “Use data to improve Discord” enabled under User Settings > Privacy & Safety.

Will update the README to say this! I didn't realize you need this, that might be why a lot of people are still ineligible.
